Repository InspireCamp-mini-project-7/cineAI-server, pull requests merged in 2025-02, with the labels that each got.

#2 init: initalize project
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/amcamp/seven/SevenApplication.java
  src/main/resources/application.properties
  src/test/java/com/amcamp/seven/SevenApplicationTests.java
Labels: ⚙️chore

#4 ⚙️chore: Swagger · 프로젝트 디렉토리 · Spring Actuator 설정
  build.gradle
  src/main/java/com/amcamp/seven/infra/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️chore

#6 chore: Spotless Code Formatter와 Spring Security 설정
  build.gradle
  scripts/pre-commit
  src/main/java/com/amcamp/seven/SevenApplication.java
  src/main/java/com/amcamp/seven/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/seven/global/config/swagger/SwaggerConfig.java
  src/main/java/com/amcamp/seven/infra/config/SwaggerConfig.java
  src/test/java/com/amcamp/seven/SevenApplicationTests.java
Labels: ⚙️chore

#8 chore: 공통 응답 로직 설정
  settings.gradle
  src/main/java/com/amcamp/cineAI/CineAIApplication.java
  src/main/java/com/amcamp/cineAI/global/common/response/CommonResponse.java
  src/main/java/com/amcamp/cineAI/global/common/response/CommonResponseAdvice.java
  src/main/java/com/amcamp/cineAI/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/cineAI/global/config/swagger/SwaggerConfig.java
  src/test/java/com/amcamp/cineAI/CineAIApplicationTests.java
Labels: ⚙️chore

#16 chore: 공통 오류 처리 (#13)
  src/main/java/com/amcamp/cineAI/global/error/ErrorControllerAdvice.java
  src/main/java/com/amcamp/cineAI/global/error/ErrorResponse.java
  src/main/java/com/amcamp/cineAI/global/error/exception/CustomException.java
  src/main/java/com/amcamp/cineAI/global/error/exception/ErrorCode.java
  src/test/java/com/amcamp/cineAI/global/error/ErrorControllerAdviceTest.java
Labels: ⚙️chore

#17 feat: 소셜 로그인 구현
  build.gradle
  src/main/java/com/amcamp/cineAI/domain/auth/api/AuthController.java
  src/main/java/com/amcamp/cineAI/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/cineAI/domain/auth/application/KakaoService.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/KakaoTokenResponseDto.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/amcamp/cineAI/domain/user/dao/MemberRepository.java
  src/main/java/com/amcamp/cineAI/domain/user/domain/Member.java
  src/main/java/com/amcamp/cineAI/domain/user/domain/MemberRole.java
  src/main/java/com/amcamp/cineAI/domain/user/domain/MemberStatus.java
  src/main/java/com/amcamp/cineAI/global/common/constants/SecurityConstants.java
  src/main/java/com/amcamp/cineAI/global/util/CookieUtil.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/amcamp/cineAI/CineAIApplicationTests.java
  src/test/java/com/amcamp/cineAI/global/error/ErrorControllerAdviceTest.java
Labels: ✨feat

#20 feat: 로그인한 멤버 조회 유틸리티 구현
  src/main/java/com/amcamp/cineAI/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/cineAI/domain/auth/application/KakaoService.java
  src/main/java/com/amcamp/cineAI/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/amcamp/cineAI/domain/auth/domain/RefreshToken.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/ProfileInfoResponse.java
  src/main/java/com/amcamp/cineAI/domain/member/api/MemberController.java
  src/main/java/com/amcamp/cineAI/domain/member/application/MemberService.java
  src/main/java/com/amcamp/cineAI/domain/member/dao/MemberRepository.java
  src/main/java/com/amcamp/cineAI/domain/member/domain/Member.java
  src/main/java/com/amcamp/cineAI/domain/member/domain/MemberRole.java
  src/main/java/com/amcamp/cineAI/domain/member/domain/MemberStatus.java
  src/main/java/com/amcamp/cineAI/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/cineAI/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/cineAI/global/util/CookieUtil.java
  src/main/java/com/amcamp/cineAI/global/util/MemberUtil.java
Labels: ✨feat

#22 feat: 로그아웃 · 회원탈퇴 · 회원정보 수정 기능
  src/main/java/com/amcamp/cineAI/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/amcamp/cineAI/domain/member/api/MemberController.java
  src/main/java/com/amcamp/cineAI/domain/member/application/MemberService.java
  src/main/java/com/amcamp/cineAI/domain/member/domain/Member.java
  src/main/java/com/amcamp/cineAI/domain/member/dto/request/MemberEditRequest.java
Labels: ✨feat

#24 fix: Swagger 관련 오류 수정
  build.gradle
  src/main/java/com/amcamp/cineAI/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/ProfileInfoResponse.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/amcamp/cineAI/domain/member/api/MemberController.java
  src/main/java/com/amcamp/cineAI/domain/member/dto/request/MemberEditRequest.java
  src/main/java/com/amcamp/cineAI/domain/member/dto/response/MemberInfoResponse.java
Labels: 🐛fix

#26 feat(domain/llm): 영화 추천 및 Q&A API 구현
  src/main/java/com/amcamp/cineAI/domain/llm/api/MovieQAController.java
  src/main/java/com/amcamp/cineAI/domain/llm/api/MovieRecommendationController.java
  src/main/java/com/amcamp/cineAI/domain/llm/application/LLMService.java
  src/main/java/com/amcamp/cineAI/domain/llm/application/MovieQAService.java
  src/main/java/com/amcamp/cineAI/domain/llm/application/MovieRecommendationService.java
  src/main/java/com/amcamp/cineAI/domain/llm/application/PromptService.java
  src/main/java/com/amcamp/cineAI/domain/llm/dto/request/QARequest.java
  src/main/java/com/amcamp/cineAI/domain/llm/dto/request/RankingRequest.java
  src/main/java/com/amcamp/cineAI/domain/llm/dto/response/MovieAnswerResponse.java
  src/main/java/com/amcamp/cineAI/domain/llm/dto/response/MovieRecommendationResponse.java
  src/main/resources/prompts/movie-qa.txt
  src/main/resources/prompts/movie-ranking.txt
Labels: ✨feat

#28 feat: 최신 영화 추가, 최신 영화 목록 조회, 영화 상세 정보 조회 기능 구현
  build.gradle
  src/main/generated/com/amcamp/cineAI/domain/auth/domain/QRefreshToken.java
  src/main/generated/com/amcamp/cineAI/domain/common/model/QBaseTimeEntity.java
  src/main/generated/com/amcamp/cineAI/domain/member/domain/QMember.java
  src/main/generated/com/amcamp/cineAI/domain/movie/domain/QMovie.java
  src/main/java/com/amcamp/cineAI/domain/common/model/BaseTimeEntity.java
  src/main/java/com/amcamp/cineAI/domain/movie/api/MovieController.java
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepository.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepositoryCustom.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepositoryImpl.java
  src/main/java/com/amcamp/cineAI/domain/movie/domain/Movie.java
  src/main/java/com/amcamp/cineAI/domain/movie/domain/MovieStatus.java
  src/main/java/com/amcamp/cineAI/domain/movie/dto/request/NewMovieCreateRequest.java
  src/main/java/com/amcamp/cineAI/domain/movie/dto/response/BasicMovieInfoResponse.java
  src/main/java/com/amcamp/cineAI/domain/movie/dto/response/MovieInfoResponse.java
  src/main/java/com/amcamp/cineAI/global/config/jpa/JPAConfig.java
  src/main/java/com/amcamp/cineAI/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/cineAI/global/util/MemberUtil.java
Labels: ✨feat

#31 feat: 관리자 로그인 기능 (#30)
  src/main/java/com/amcamp/cineAI/domain/member/api/MemberController.java
Labels: ✨feat

#36 fix: 쿠키 전송 오류 수정
  src/main/java/com/amcamp/cineAI/domain/member/api/MemberController.java
  src/main/java/com/amcamp/cineAI/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/cineAI/global/util/CookieUtil.java
  src/main/java/com/amcamp/cineAI/global/util/MemberUtil.java
Labels: 🐛fix

#38 feat: 최초로그인 여부 반환 기능 구현
  src/main/java/com/amcamp/cineAI/domain/auth/api/AuthController.java
  src/main/java/com/amcamp/cineAI/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/cineAI/domain/auth/domain/LoginStatus.java
  src/main/java/com/amcamp/cineAI/domain/auth/dto/response/FirstLoginResponse.java
  src/main/java/com/amcamp/cineAI/global/config/security/WebSecurityConfig.java
Labels: ✨feat

#42 feat: 초기 설정 영화 목록 조회 & 외부 api 연동
  src/main/java/com/amcamp/cineAI/domain/movie/MovieConstants.java
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
Labels: ✨feat

#44 feat: 영화 검색 기능
  src/main/java/com/amcamp/cineAI/domain/movie/api/MovieController.java
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepository.java
  src/main/java/com/amcamp/cineAI/domain/movie/dto/response/MovieInfoResponseList.java
  src/main/resources/application.yml
Labels: ✨feat

#49 feat : 추천 목록 기능 구현
  src/main/java/com/amcamp/cineAI/domain/llm/application/PromptService.java
  src/main/java/com/amcamp/cineAI/domain/movie/api/MovieController.java
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MoviePreferenceRepository.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepositoryCustom.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepositoryImpl.java
  src/main/java/com/amcamp/cineAI/domain/movie/dto/response/MoviePreferenceResponse.java
  src/main/java/com/amcamp/cineAI/global/error/exception/ErrorCode.java
  src/main/resources/kmdb/zNex~$harekmdb_data.csv
  src/main/resources/prompts/movie-search.txt
Labels: ✨feat

#57 Refactor/50-s3-storage
  build.gradle
  src/main/java/com/amcamp/cineAI/domain/movie/api/MovieController.java
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
  src/main/java/com/amcamp/cineAI/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/cineAI/global/util/FileUtils.java
  src/main/java/com/amcamp/cineAI/infra/config/Aws/AwsS3Config.java
  src/main/resources/application.yml
Labels: ♻️refactor

#58 feat:KMDB 데이터 초기 설정 수정
  src/main/java/com/amcamp/cineAI/domain/movie/application/MovieService.java
  src/main/java/com/amcamp/cineAI/domain/movie/dao/MovieRepository.java
  src/main/java/com/amcamp/cineAI/global/init/MovieDbInitializer.java
  src/main/resources/application.yml
Labels: ♻️refactor

#61 fix:spotless run
  Dockerfile
  src/main/java/com/amcamp/cineAI/domain/movie/api/MovieController.java
Labels: 🐛fix

#65 fix: 회원탈퇴 후 재가입 오류 수정
  src/main/java/com/amcamp/cineAI/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/cineAI/global/config/security/WebSecurityConfig.java
Labels: 🐛fix
